openapi: 3.0.3
info:
  title: SkyTracker ITB - OpenAPI 3.0
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with   time, we can improve the API in general, and expose some of the new features in OAS3.
    
    
    https://editor.swagger.io/

  version: 1.0.11
servers:
  - url: localhost:8080/api
paths:
  /sats_by_user:
    get:
      summary: Number of satellites followed by each user
      description: If the user does not follow any satellite it will not appear.

      responses:
        '200':
          description: A Json array of map<String, String>
          content:
            application/json:
              schema:
                type: object
                properties:
                  naim.gomez.7e5@itb.cat:
                    type: integer
                    description: The user ID.